export const VALIDATE_TOOLS = [
  {
    id: 'validator',
    name: 'JSON Validator',
    description: 'Real-time JSON validation with detailed error messages',
    icon: 'CheckCircle',
    path: '/tools/validator',
    tags: ['validate', 'check', 'errors'],
  },
  {
    id: 'repair',
    name: 'JSON Repair',
    description: 'Fix malformed JSON automatically',
    icon: 'BuildCircle',
    path: '/tools/repair',
    tags: ['repair', 'fix', 'malformed'],
  },
  {
    id: 'error-analyzer',
    name: 'Error Analyzer',
    description: 'Human-readable error explanations',
    icon: 'ErrorOutline',
    path: '/tools/error-analyzer',
    tags: ['analyze', 'error', 'debug'],
  },
  {
    id: 'pretty-print',
    name: 'Pretty Print',
    description: 'Format JSON with custom indentation',
    icon: 'FormatAlignLeft',
    path: '/tools/pretty-print',
    tags: ['format', 'indent', 'beautify'],
  },
  {
    id: 'minify',
    name: 'Minify',
    description: 'Compress JSON and remove whitespace',
    icon: 'Compress',
    path: '/tools/minify',
    tags: ['minify', 'compress', 'size'],
  },
  {
    id: 'sort-keys',
    name: 'Sort Keys',
    description: 'Recursively sort object keys',
    icon: 'SortByAlpha',
    path: '/tools/sort-keys',
    tags: ['sort', 'order', 'keys'],
  },
  {
    id: 'escape-unescape',
    name: 'Escape/Unescape',
    description: 'Convert JSON strings to escaped text',
    icon: 'SwapHoriz',
    path: '/tools/escape-unescape',
    tags: ['escape', 'unescape', 'string'],
  },
  {
    id: 'stringify',
    name: 'Stringify',
    description: 'Convert objects to escaped JSON strings',
    icon: 'Code',
    path: '/tools/stringify',
    tags: ['stringify', 'string', 'convert'],
  },
]

export const VIEW_TOOLS = [
  {
    id: 'tree-viewer',
    name: 'Tree Viewer',
    description: 'Explore JSON as an interactive tree',
    icon: 'AccountTree',
    path: '/tools/tree-viewer',
    tags: ['tree', 'view', 'explore'],
  },
  {
    id: 'table-viewer',
    name: 'Table Viewer',
    description: 'View arrays as sortable tables',
    icon: 'TableChart',
    path: '/tools/table-viewer',
    tags: ['table', 'array', 'view'],
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare two JSON documents',
    icon: 'CompareArrows',
    path: '/tools/json-diff',
    tags: ['diff', 'compare', 'changes'],
  },
  {
    id: 'jsonpath-query',
    name: 'JSONPath Query',
    description: 'Execute JSONPath expressions',
    icon: 'ManageSearch',
    path: '/tools/jsonpath-query',
    tags: ['query', 'jsonpath', 'search'],
  },
  {
    id: 'json-search',
    name: 'JSON Search',
    description: 'Search keys and values with regex',
    icon: 'Search',
    path: '/tools/json-search',
    tags: ['search', 'find', 'regex'],
  },
  {
    id: 'size-analyzer',
    name: 'Size Analyzer',
    description: 'Analyze JSON structure and size',
    icon: 'BarChart',
    path: '/tools/size-analyzer',
    tags: ['analyze', 'size', 'stats'],
  },
  {
    id: 'flatten-json',
    name: 'Flatten JSON',
    description: 'Convert to dot notation',
    icon: 'FlattenOutlined',
    path: '/tools/flatten-json',
    tags: ['flatten', 'dot', 'notation'],
  },
]

export const CONVERT_TOOLS = [
  {
    id: 'yaml-converter',
    name: 'YAML Converter',
    description: 'Convert between JSON and YAML',
    icon: 'Transform',
    path: '/tools/yaml-converter',
    tags: ['yaml', 'convert', 'transform'],
  },
  {
    id: 'csv-converter',
    name: 'CSV Converter',
    description: 'Convert between JSON and CSV',
    icon: 'DataUsage',
    path: '/tools/csv-converter',
    tags: ['csv', 'convert', 'export'],
  },
  {
    id: 'base64-tools',
    name: 'Base64 Tools',
    description: 'Encode/decode Base64 strings',
    icon: 'CastConnected',
    path: '/tools/base64-tools',
    tags: ['base64', 'encode', 'decode'],
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and verify JWT tokens',
    icon: 'LockOpen',
    path: '/tools/jwt-decoder',
    tags: ['jwt', 'token', 'decode'],
  },
  {
    id: 'schema-generator',
    name: 'Schema Generator',
    description: 'Generate JSON Schema from data',
    icon: 'Architecture',
    path: '/tools/schema-generator',
    tags: ['schema', 'generate', 'json-schema'],
  },
]
